apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girobuntu
  name: girobuntu
spec:
  containers:
  - image: ubuntu
    name: girobuntu
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
