apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: girus
    ports:
    - containerPort: 80
  - image: alpine
    name: strigus
    args:
    - sleep
    - "1800"
